CREATE DATABASE AUTORIZADOR_BANCOABC;
USE AUTORIZADOR_BANCOABC;

CREATE TABLE TIPOS_TARJETAS_TB( -- CREDITO -- DEBITO
	TIPO_TARJ_ID INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO_TARJ_Nombre VARCHAR(30) NOT NULL UNIQUE, 
    TIPO_TARJ_Estado BOOLEAN NOT NULL DEFAULT 1 
); 

CREATE TABLE TARJETAS_TB(
	TARJETA_ID INT PRIMARY KEY AUTO_INCREMENT,
    TARJETA_Numero VARCHAR(255) NOT NULL UNIQUE,
    TARJETA_PIN VARCHAR(255) NOT NULL,
    TARJETA_FechaVencimiento VARCHAR(255) NOT NULL,
    TARJETA_NumVerificacion VARCHAR(255) NOT NULL,
    TARJETA_TIPO_TARJ_ID INT NOT NULL, -- FK
    TARJETA_Estado BOOLEAN NOT NULL DEFAULT 1,
    
	FOREIGN KEY(TARJETA_TIPO_TARJ_ID)
		REFERENCES TIPOS_TARJETAS_TB(TIPO_TARJ_ID)
);

CREATE TABLE CUENTAS_TB(
	CUENTA_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUENTA_TARJETA_ID INT NOT NULL, -- FK
    CUENTA_MontoAdelantadoEfectivo DECIMAL(10,2), -- NULL si la tarjeta es de débito
    CUENTA_Estado BOOLEAN NOT NULL DEFAULT 1,
    
    FOREIGN KEY(CUENTA_TARJETA_ID)
		REFERENCES TARJETAS_TB(TARJETA_ID),
    
    CONSTRAINT UQ_CUENTA_TARJETA
		UNIQUE(CUENTA_TARJETA_ID)
);

CREATE TABLE TIPOS_TRANSACCIONES_TB( -- RETIRO, CONSULTA, CAMBIO DE PIN
	TIPO_TRANSAC_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_TRANSAC_Nombre VARCHAR(50) NOT NULL UNIQUE,
    TIPO_TRANSAC_Estado BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE ESTADOS_TRANSACCIONES_TB( -- PENDIENTE
	EST_TRANSAC_ID INT PRIMARY KEY AUTO_INCREMENT,
    EST_TRANSAC_Nombre VARCHAR(50) NOT NULL UNIQUE,
    EST_TRANSAC_Estado BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE TRANSACCIONES_TB(
	TRANSAC_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSAC_CUENTA_ID INT NOT NULL, -- FK
    TRANSAC_TIPO_TRANSAC_ID INT NOT NULL, -- FK
    TRANSAC_Monto DECIMAL(10,2) NOT NULL,
    TRANSAC_ESTADO_ID INT NOT NULL, -- FK
    
    FOREIGN KEY(TRANSAC_CUENTA_ID)
		REFERENCES CUENTAS_TB(CUENTA_ID),
	FOREIGN KEY(TRANSAC_TIPO_TRANSAC_ID)
		REFERENCES TIPOS_TRANSACCIONES_TB(TIPO_TRANSAC_ID),
	FOREIGN KEY(TRANSAC_ESTADO_ID)
		REFERENCES ESTADOS_TRANSACCIONES_TB(EST_TRANSAC_ID)
);

CREATE TABLE CAJEROS_TB( -- SIM-001 -- SIM-002 -- SIM-003 -->
	CAJ_ID INT PRIMARY KEY AUTO_INCREMENT,
    CAJ_ID_Identificador VARCHAR(10) NOT NULL UNIQUE,
    CAJ_Estado BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE TRANSACCIONES_CAJEROS_TB(
	TRANSAC_CAJ_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSAC_CAJ_CAJ_ID INT NOT NULL, -- FK
    TRANSAC_CAJ_TRANSAC_ID INT NOT NULL UNIQUE, -- FK
    TRANSAC_FechaHora DATETIME NOT NULL,
    
    FOREIGN KEY(TRANSAC_CAJ_CAJ_ID)
		REFERENCES CAJEROS_TB(CAJ_ID ),
	FOREIGN KEY(TRANSAC_CAJ_TRANSAC_ID)
		REFERENCES TRANSACCIONES_TB(TRANSAC_ID)
);
