CREATE DATABASE AUTORIZADOR_BANCOABC;
USE AUTORIZADOR_BANCOABC;

CREATE TABLE TIPOS_TARJETAS_TB( 
	TIPO_TARJ_ID INT PRIMARY KEY AUTO_INCREMENT, -- PK
    TIPO_TARJ_Nombre VARCHAR(30) NOT NULL UNIQUE, -- CREDITO -- DEBITO
    TIPO_TARJ_Estado BOOLEAN NOT NULL DEFAULT 1 
); 

CREATE TABLE TARJETAS_TB(
	TARJETA_ID INT PRIMARY KEY AUTO_INCREMENT, -- PK
    TARJETA_Numero VARCHAR(255) NOT NULL UNIQUE,
    TARJETA_PIN VARCHAR(255) NOT NULL,
    TARJETA_FechaVencimiento VARCHAR(255) NOT NULL,
    TARJETA_NumVerificacion VARCHAR(255) NOT NULL,
    TARJETA_TIPO_TARJ_ID INT NOT NULL, -- FK
    TARJETA_Estado BOOLEAN NOT NULL DEFAULT 1,
    
	FOREIGN KEY(TARJETA_TIPO_TARJ_ID)
		REFERENCES TIPOS_TARJETAS_TB(TIPO_TARJ_ID)
);

CREATE TABLE CUENTAS_TB(
	CUENTA_ID INT PRIMARY KEY AUTO_INCREMENT, -- PK
    CUENTA_TARJETA_ID INT NULL, -- FK -- NULL Hasta que sea agregada una tarjeta
    CUENTA_MontoAdelantadoEfectivo DECIMAL(10,2), -- NULL si la tarjeta es de débito
    CUENTA_Estado BOOLEAN NOT NULL DEFAULT 1,
    
    FOREIGN KEY(CUENTA_TARJETA_ID)
		REFERENCES TARJETAS_TB(TARJETA_ID),
    
    CONSTRAINT UQ_CUENTA_TARJETA
		UNIQUE(CUENTA_TARJETA_ID)
);

CREATE TABLE PERSONAS_TB(
	PER_ID INT PRIMARY KEY AUTO_INCREMENT, -- PK
    PER_IDENTIFICACION VARCHAR(25) NOT NULL,
    PER_NOMBRE VARCHAR(150) NOT NULL,
    PER_APELLIDO1 VARCHAR(150) NOT NULL,
    PERS_APELLIDO2 VARCHAR(150) NOT NULL,
    PER_CORREO VARCHAR(150) NOT NULL,
    
    CONSTRAINT UQ_PER_IDENTIFICACION
		UNIQUE (PER_IDENTIFICACION),
        
	CONSTRAINT UQ_PER_CORREO
		UNIQUE (PER_CORREO)
);

CREATE TABLE PERSONASXCUENTAS(
	PERXCU_ID INT PRIMARY KEY AUTO_INCREMENT, -- PK
    PERXCU_PER_ID INT NOT NULL, -- FK
    PERXCU_CUENTA_ID INT NOT NULL, -- FK
    
	FOREIGN KEY (PERXCU_PER_ID)
		REFERENCES PERSONAS_TB (PER_ID),
        
	FOREIGN KEY (PERXCU_CUENTA_ID)
		REFERENCES CUENTAS_TB (CUENTA_ID),
        
	CONSTRAINT UQ_PERSONA_CUENTA
		UNIQUE (PERXCU_PER_ID, PERXCU_CUENTA_ID)
);

CREATE TABLE TIPOS_TRANSACCIONES_TB( 
	TIPO_TRANSAC_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_TRANSAC_Nombre VARCHAR(50) NOT NULL UNIQUE, -- RETIRO, CONSULTA, CAMBIO DE PIN
    TIPO_TRANSAC_Estado BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE ESTADOS_TRANSACCIONES_TB( -- PENDIENTE
	EST_TRANSAC_ID INT PRIMARY KEY AUTO_INCREMENT,
    EST_TRANSAC_Nombre VARCHAR(50) NOT NULL UNIQUE,
    EST_TRANSAC_Estado BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE TRANSACCIONES_TB(
	TRANSAC_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSAC_CUENTA_ID INT NOT NULL, -- FK
    TRANSAC_TIPO_TRANSAC_ID INT NOT NULL, -- FK
    TRANSAC_Monto DECIMAL(10,2) NOT NULL,
    TRANSAC_ESTADO_ID INT NOT NULL, -- FK
    
    FOREIGN KEY(TRANSAC_CUENTA_ID)
		REFERENCES CUENTAS_TB(CUENTA_ID),
	FOREIGN KEY(TRANSAC_TIPO_TRANSAC_ID)
		REFERENCES TIPOS_TRANSACCIONES_TB(TIPO_TRANSAC_ID),
	FOREIGN KEY(TRANSAC_ESTADO_ID)
		REFERENCES ESTADOS_TRANSACCIONES_TB(EST_TRANSAC_ID)
);

CREATE TABLE CAJEROS_TB( -- O tiendas
	CAJ_ID INT PRIMARY KEY AUTO_INCREMENT,
    CAJ_ID_Identificador VARCHAR(10) NOT NULL UNIQUE, -- SIM-001 -- SIM-002 -- SIM-003 -->
    CAJ_Estado BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE TRANSACCIONES_CAJEROS_TB(
	TRANSAC_CAJ_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSAC_CAJ_CAJ_ID INT NOT NULL, -- FK
    TRANSAC_CAJ_TRANSAC_ID INT NOT NULL UNIQUE, -- FK
    TRANSAC_FechaHora DATETIME NOT NULL,
    
    FOREIGN KEY(TRANSAC_CAJ_CAJ_ID)
		REFERENCES CAJEROS_TB(CAJ_ID ),
	FOREIGN KEY(TRANSAC_CAJ_TRANSAC_ID)
		REFERENCES TRANSACCIONES_TB(TRANSAC_ID)
);
