USE AUTORIZADOR_BANCOABC;

-- PARA VALIDAR DATOS AUT1
SELECT 
	TARJ.TARJETA_Numero AS 'Numero de Tarjeta', -- Cifrado
    TARJ.TARJETA_PIN AS 'PIN', -- Cifrado
    TARJ.TARJETA_NumVerificacion AS 'Numero Verificacion', -- Cifrado
    TARJ.TARJETA_FechaVencimiento ' Fecha de Vencimiento', -- Cifrado
    TT.TIPO_TARJ_Nombre 'Tipo de Tarjeta', -- Crédito o Débito 
    CU.CUENTA_MontoAdelantadoEfectivo 'Adelanto de Efectivo' -- Para tarjetas de crédito, las de debito tienen 0.00 o NULL por defecto
FROM TIPOS_TARJETAS_TB TT
	INNER JOIN TARJETAS_TB TARJ
		ON TT.TIPO_TARJ_ID = TARJ.TARJETA_TIPO_TARJ_ID
	INNER JOIN CUENTAS_TB CU
		ON TARJ.TARJETA_ID = CU.CUENTA_TARJETA_ID;
	

-- PARA VALIDAR CAJEROS
SELECT CAJ_ID_Identificador
FROM CAJEROS_TB
WHERE CAJ_Estado = 1;


-- AUT5 - SP PARA TARJETAS DE CREDITO
DELIMITER //

CREATE PROCEDURE SP_AUT5_ADELANTO_EFECTIVO(
    IN P_NUMERO_TARJETA VARCHAR(255), -- Cifrado
    IN P_IDENTIFICADOR_CAJERO VARCHAR(15), -- C
    IN P_TIPO_TRANSACCION VARCHAR(15), --
    IN P_MONTO_TRANSACCION DECIMAL(10,2),
    
    OUT P_RESPUESTA INT
)
BEGIN
	PROC: BEGIN
		
		DECLARE V_TARJETA_ID INT;
		DECLARE V_CAJERO_ID INT;
		DECLARE V_TRANSACCION_ID INT;
		
		-- VALIDAR CAJERO
		SELECT CAJ_ID
		INTO V_CAJERO_ID
		FROM CAJEROS_TB
		WHERE CAJ_ID_Identificador = P_IDENTIFICADOR_CAJERO
		  AND CAJ_Estado = 1
		LIMIT 1;

		IF V_CAJERO_ID IS NULL THEN
			SET P_RESPUESTA = 2; -- DATOS INCORRECTOS
			LEAVE PROC;
		END IF;
		
		-- VALIDAR TARJETA
		SELECT TARJETA_ID
		INTO V_TARJETA_ID
		FROM TARJETAS_TB
		WHERE TARJETA_Numero = P_NUMERO_TARJETA
			AND TARJETA_Estado = 1
		LIMIT 1;
		
		IF V_TARJETA_ID IS NULL THEN
			SET P_RESPUESTA = 2; -- DATOS INCORRECTOS
			LEAVE PROC;
		END IF;
			
		-- VALIDAR TIPO DE TRANSACCIÓN
		IF UPPER(
			   REPLACE(P_TIPO_TRANSACCION, 'Ó', 'O')
		) != 'CONFIRMACION' THEN
			SET P_RESPUESTA = 5; -- ERROR NO CONTROLADO
			LEAVE PROC;
		END IF;
		
		-- Valida monto de la tarjeta
		IF NOT EXISTS (
			SELECT 1
			FROM CUENTAS_TB
			WHERE CUENTA_TARJETA_ID = V_TARJETA_ID
			  AND CUENTA_MontoAdelantadoEfectivo >= P_MONTO_TRANSACCION
		) THEN
			SET P_RESPUESTA = 1; -- FONDOS INSUFICIENTES
			LEAVE PROC;
		END IF;
		
		START TRANSACTION;
		
		-- Actualiza el monto de adelanto de efectivo
		UPDATE CUENTAS_TB 
		SET CUENTA_MontoAdelantadoEfectivo = 
			CUENTA_MontoAdelantadoEfectivo - P_MONTO_TRANSACCION
		WHERE CUENTA_TARJETA_ID = V_TARJETA_ID;
		
		INSERT INTO TRANSACCIONES_TB (
			TRANSAC_CUENTA_ID, 
			TRANSAC_TIPO_TRANSAC_ID, 
			TRANSAC_MONTO, 
			TRANSAC_ESTADO_ID
		) 
		SELECT
		CU.CUENTA_ID,
		TT.TIPO_TRANSAC_ID,
		P_MONTO_TRANSACCION,
		ET.EST_TRANSAC_ID
		FROM CUENTAS_TB CU
		JOIN TIPOS_TRANSACCIONES_TB TT
			ON TT.TIPO_TRANSAC_Nombre = 'Retiro'
		JOIN ESTADOS_TRANSACCIONES_TB ET
			ON ET.EST_TRANSAC_Nombre = 'Pendiente'
		WHERE CU.CUENTA_TARJETA_ID = V_TARJETA_ID;
		
		SET V_TRANSACCION_ID = LAST_INSERT_ID();
		
		INSERT INTO TRANSACCIONES_CAJEROS_TB (
		TRANSAC_CAJ_CAJ_ID,
		TRANSAC_CAJ_TRANSAC_ID,
		TRANSAC_FechaHora
		)
		VALUES (
			V_CAJERO_ID,
			V_TRANSACCION_ID,
			NOW()
		);
		
		COMMIT;
		SET P_RESPUESTA = 0; -- OK
		
	END PROC;
END//

DELIMITER ;


-- AUT2_Consulta_Credito
SELECT 
	TAR.TARJETA_Numero AS 'Numero de Tarjeta',
    TT.TIPO_TARJ_Nombre AS 'Tipo de Tarjeta',
    CU.CUENTA_MontoAdelantadoEfectivo AS 'Saldo Disponible Adelanto de Efectivo'
FROM TIPOS_TARJETAS_TB TT
INNER JOIN TARJETAS_TB TAR
	ON TT.TIPO_TARJ_ID = TAR.TARJETA_TIPO_TARJ_ID
INNER JOIN CUENTAS_TB CU
	ON TAR.TARJETA_ID = CU.CUENTA_TARJETA_ID
WHERE TT.TIPO_TARJ_Nombre = 'Credito' 
	AND TAR.TARJETA_Estado = 1;
    


-- AUT3_CambioPIN
DELIMITER //

CREATE PROCEDURE SP_AUT3_CAMBIOPIN(
    IN P_COD_CAJERO VARCHAR(15),
    IN P_NUM_TARJETA VARCHAR(255),
    IN P_PIN_ACTUAL VARCHAR(255),
    IN P_PIN_NUEVO VARCHAR(255),
    
    OUT P_RESPUESTA_OUT INT
)
BEGIN
    PROC: BEGIN

        DECLARE V_TARJETA_ID INT;
        DECLARE V_CAJERO_ID INT;
        DECLARE V_TRANSACCION_ID INT;

        DECLARE EXIT HANDLER FOR SQLEXCEPTION
        BEGIN
            ROLLBACK;
            SET P_RESPUESTA_OUT = 5; -- ERROR NO CONTROLADO
        END;

        -- VALIDAR CAJERO
        SELECT CAJ_ID
        INTO V_CAJERO_ID
        FROM CAJEROS_TB
        WHERE CAJ_ID_Identificador = P_COD_CAJERO
          AND CAJ_Estado = 1
        LIMIT 1;

        IF V_CAJERO_ID IS NULL THEN
            SET P_RESPUESTA_OUT = 2; -- DATOS INCORRECTOS
            LEAVE PROC;
        END IF;

        -- VALIDAR TARJETA Y PIN
        SELECT TARJETA_ID
        INTO V_TARJETA_ID
        FROM TARJETAS_TB
        WHERE TARJETA_Numero = P_NUM_TARJETA
          AND TARJETA_PIN = P_PIN_ACTUAL
          AND TARJETA_Estado = 1
        LIMIT 1;

        IF V_TARJETA_ID IS NULL THEN
            SET P_RESPUESTA_OUT = 2; -- DATOS INCORRECTOS
            LEAVE PROC;
        END IF;

        START TRANSACTION;

        -- CAMBIO DE PIN
        UPDATE TARJETAS_TB
        SET TARJETA_PIN = P_PIN_NUEVO
        WHERE TARJETA_ID = V_TARJETA_ID;

        -- REGISTRO DE LA TRANSACCIÓN
        INSERT INTO TRANSACCIONES_TB (
            TRANSAC_CUENTA_ID,
            TRANSAC_TIPO_TRANSAC_ID,
            TRANSAC_MONTO,
            TRANSAC_ESTADO_ID
        )
        SELECT
            CU.CUENTA_ID,
            TT.TIPO_TRANSAC_ID,
            0.00,
            ET.EST_TRANSAC_ID
        FROM CUENTAS_TB CU
        JOIN TIPOS_TRANSACCIONES_TB TT
            ON TT.TIPO_TRANSAC_Nombre = 'Cambio de PIN'
        JOIN ESTADOS_TRANSACCIONES_TB ET
            ON ET.EST_TRANSAC_Nombre = 'Completada'
        WHERE CU.CUENTA_TARJETA_ID = V_TARJETA_ID;

        SET V_TRANSACCION_ID = LAST_INSERT_ID();

        -- RELACIÓN TRANSACCIÓN / CAJERO
        INSERT INTO TRANSACCIONES_CAJEROS_TB (
            TRANSAC_CAJ_CAJ_ID,
            TRANSAC_CAJ_TRANSAC_ID,
            TRANSAC_FechaHora
        )
        VALUES (
            V_CAJERO_ID,
            V_TRANSACCION_ID,
            NOW()
        );

        COMMIT;
        SET P_RESPUESTA_OUT = 0; -- OK

    END PROC;
END//

DELIMITER //

CREATE PROCEDURE REGISTRAR_PERSONA_SP(
    IN IDENTIFICACION VARCHAR(25),
    IN NOMBRE VARCHAR(150),
    IN PRIMER_APELLIDO VARCHAR(150),
    IN SEGUNDO_APELLIDO VARCHAR(150),
    IN CORREO VARCHAR(150)
)
BEGIN
    -- Validación: campos obligatorios no vacíos
    IF TRIM(IDENTIFICACION) = '' OR IDENTIFICACION IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Error: La identificación es obligatoria.';
    END IF;

    IF TRIM(NOMBRE) = '' OR NOMBRE IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Error: El nombre es obligatorio.';
    END IF;

    IF TRIM(PRIMER_APELLIDO) = '' OR PRIMER_APELLIDO IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Error: El primer apellido es obligatorio.';
    END IF;

    IF TRIM(CORREO) = '' OR CORREO IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Error: El correo es obligatorio.';
    END IF;

    -- Validación: formato de correo básico
    IF CORREO NOT LIKE '%_@__%.__%' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Error: El formato del correo no es válido.';
    END IF;

    -- Validación: identificación no duplicada
    IF EXISTS (SELECT 1 FROM PERSONAS_TB WHERE PER_IDENTIFICACION = IDENTIFICACION) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Error: La identificación ya está registrada.';
    END IF;

    -- Validación: correo no duplicado
    IF EXISTS (SELECT 1 FROM PERSONAS_TB WHERE PER_CORREO = CORREO) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Error: El correo ya está registrado.';
    END IF;

    -- INSERT
    INSERT INTO PERSONAS_TB (
        PER_IDENTIFICACION,
        PER_NOMBRE,
        PER_APELLIDO1,
        PERS_APELLIDO2,
        PER_CORREO
    ) VALUES (
        TRIM(IDENTIFICACION),
        TRIM(NOMBRE),
        TRIM(PRIMER_APELLIDO),
        TRIM(SEGUNDO_APELLIDO),
        TRIM(CORREO)
    );

END //

DELIMITER ;




