//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutorizadorWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsulta", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RespuestaConsulta : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        private string SaldoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSimple", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RespuestaSimple : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutorizadorWS.IAutorizadorService")]
    public interface IAutorizadorService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizadorService/ConsultarSaldo", ReplyAction="http://tempuri.org/IAutorizadorService/ConsultarSaldoResponse")]
        System.Threading.Tasks.Task<AutorizadorWS.RespuestaConsulta> ConsultarSaldoAsync(string numeroTarjeta, string cvv, string fechaVencimiento, string identificadorCajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizadorService/CambiarPIN", ReplyAction="http://tempuri.org/IAutorizadorService/CambiarPINResponse")]
        System.Threading.Tasks.Task<AutorizadorWS.RespuestaSimple> CambiarPINAsync(string numeroTarjeta, string pinActual, string pinNuevo, string fechaVencimiento, string cvv, string identificadorCajero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAutorizadorServiceChannel : AutorizadorWS.IAutorizadorService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AutorizadorServiceClient : System.ServiceModel.ClientBase<AutorizadorWS.IAutorizadorService>, AutorizadorWS.IAutorizadorService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AutorizadorServiceClient() : 
                base(AutorizadorServiceClient.GetDefaultBinding(), AutorizadorServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAutorizadorService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutorizadorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AutorizadorServiceClient.GetBindingForEndpoint(endpointConfiguration), AutorizadorServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutorizadorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AutorizadorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutorizadorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AutorizadorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutorizadorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AutorizadorWS.RespuestaConsulta> ConsultarSaldoAsync(string numeroTarjeta, string cvv, string fechaVencimiento, string identificadorCajero)
        {
            return base.Channel.ConsultarSaldoAsync(numeroTarjeta, cvv, fechaVencimiento, identificadorCajero);
        }
        
        public System.Threading.Tasks.Task<AutorizadorWS.RespuestaSimple> CambiarPINAsync(string numeroTarjeta, string pinActual, string pinNuevo, string fechaVencimiento, string cvv, string identificadorCajero)
        {
            return base.Channel.CambiarPINAsync(numeroTarjeta, pinActual, pinNuevo, fechaVencimiento, cvv, identificadorCajero);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAutorizadorService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAutorizadorService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:60352/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AutorizadorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAutorizadorService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AutorizadorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAutorizadorService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAutorizadorService,
        }
    }
}
