//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Autenticador_BancoABC
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/WS.Entities")]
    public partial class Usuarios : object
    {
        
        private bool EstadoField;
        
        private string PasswordField;
        
        private string TipoUsuarioField;
        
        private string UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario
        {
            get
            {
                return this.TipoUsuarioField;
            }
            set
            {
                this.TipoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardResponseOfRespuestaAutenticacionSXL5aqMd", Namespace="http://schemas.datacontract.org/2004/07/WS.Entities")]
    public partial class StandardResponseOfRespuestaAutenticacionSXL5aqMd : object
    {
        
        private WS_Autenticador_BancoABC.RespuestaAutenticacion DatosField;
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WS_Autenticador_BancoABC.RespuestaAutenticacion Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaAutenticacion", Namespace="http://schemas.datacontract.org/2004/07/WS.Entities")]
    public partial class RespuestaAutenticacion : object
    {
        
        private string IdentificacionField;
        
        private string TipoUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario
        {
            get
            {
                return this.TipoUsuarioField;
            }
            set
            {
                this.TipoUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personas", Namespace="http://schemas.datacontract.org/2004/07/WS.Entities")]
    public partial class Personas : object
    {
        
        private string CorreoField;
        
        private string IdentificacionField;
        
        private string NombreField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private WS_Autenticador_BancoABC.Usuarios UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WS_Autenticador_BancoABC.Usuarios Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/WS.Entities")]
    public partial class StandardResponseOfboolean : object
    {
        
        private bool DatosField;
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardResponseOfArrayOfPersonasSXL5aqMd", Namespace="http://schemas.datacontract.org/2004/07/WS.Entities")]
    public partial class StandardResponseOfArrayOfPersonasSXL5aqMd : object
    {
        
        private System.Collections.Generic.List<WS_Autenticador_BancoABC.Personas> DatosField;
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WS_Autenticador_BancoABC.Personas> Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardResponseOfArrayOfUsuariosSXL5aqMd", Namespace="http://schemas.datacontract.org/2004/07/WS.Entities")]
    public partial class StandardResponseOfArrayOfUsuariosSXL5aqMd : object
    {
        
        private System.Collections.Generic.List<WS_Autenticador_BancoABC.Usuarios> DatosField;
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WS_Autenticador_BancoABC.Usuarios> Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Autenticador_BancoABC.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AutenticarUsuario", ReplyAction="http://tempuri.org/IService/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfRespuestaAutenticacionSXL5aqMd> AutenticarUsuarioAsync(WS_Autenticador_BancoABC.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarPersona", ReplyAction="http://tempuri.org/IService/RegistrarPersonaResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> RegistrarPersonaAsync(WS_Autenticador_BancoABC.Personas persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarPersona", ReplyAction="http://tempuri.org/IService/ModificarPersonaResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> ModificarPersonaAsync(WS_Autenticador_BancoABC.Personas usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarPersona", ReplyAction="http://tempuri.org/IService/EliminarPersonaResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> EliminarPersonaAsync(string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarPersonas", ReplyAction="http://tempuri.org/IService/ListarPersonasResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfArrayOfPersonasSXL5aqMd> ListarPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CrearUsuario", ReplyAction="http://tempuri.org/IService/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> CrearUsuarioAsync(string identificacion, WS_Autenticador_BancoABC.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarEstadoUsuario", ReplyAction="http://tempuri.org/IService/ModificarEstadoUsuarioResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> ModificarEstadoUsuarioAsync(WS_Autenticador_BancoABC.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarUsuarios", ReplyAction="http://tempuri.org/IService/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfArrayOfUsuariosSXL5aqMd> ListarUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServiceChannel : WS_Autenticador_BancoABC.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WS_Autenticador_BancoABC.IService>, WS_Autenticador_BancoABC.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfRespuestaAutenticacionSXL5aqMd> AutenticarUsuarioAsync(WS_Autenticador_BancoABC.Usuarios usuario)
        {
            return base.Channel.AutenticarUsuarioAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> RegistrarPersonaAsync(WS_Autenticador_BancoABC.Personas persona)
        {
            return base.Channel.RegistrarPersonaAsync(persona);
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> ModificarPersonaAsync(WS_Autenticador_BancoABC.Personas usuario)
        {
            return base.Channel.ModificarPersonaAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> EliminarPersonaAsync(string identificacion)
        {
            return base.Channel.EliminarPersonaAsync(identificacion);
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfArrayOfPersonasSXL5aqMd> ListarPersonasAsync()
        {
            return base.Channel.ListarPersonasAsync();
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> CrearUsuarioAsync(string identificacion, WS_Autenticador_BancoABC.Usuarios usuario)
        {
            return base.Channel.CrearUsuarioAsync(identificacion, usuario);
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfboolean> ModificarEstadoUsuarioAsync(WS_Autenticador_BancoABC.Usuarios usuario)
        {
            return base.Channel.ModificarEstadoUsuarioAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<WS_Autenticador_BancoABC.StandardResponseOfArrayOfUsuariosSXL5aqMd> ListarUsuariosAsync()
        {
            return base.Channel.ListarUsuariosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://avert-hybrid-catalyst.ngrok-free.dev/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
